### ISSUE TITLE
create contexts directory

### ISSUE THREAD

**Issue by gagalago** [meadsteve/white-bread#45]
when I run `mix white_bread.run` without `features/contexts` directory, I have this error:
```
$ mix white_bread.run
Default context module not found in features/contexts/default_context.exs. 
Create one [Y/n]? 

loading features/contexts/default_context.exs
** (Code.LoadError) could not load /home/sigo/workspace/identificator/features/contexts/default_context.exs
    (elixir) lib/code.ex:662: Code.find_file/2
    (elixir) lib/code.ex:319: Code.load_file/2
    lib/white_bread/command_line/context_loader.ex:27: WhiteBread.CommandLine.ContextLoader.load_context_file/1
    lib/white_bread/command_line/single_context_run.ex:9: WhiteBread.CommandLine.SingleContextRun.run_single_context/3
    lib/mix/tasks/white_bread.run.ex:19: Mix.Tasks.WhiteBread.Run.run/1
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2

```

**Comment by meadsteve** [comment]
Thanks for raising this @gagalago I'll take a look. Seems like it might have been a regression in a recent commit

**Comment by meadsteve** [comment]
@gagalago I've just tagged up and release version 2.6.1 that should fix your issue. Looks like I never had any code to create the directory if it didn't already exist.

**Comment by gagalago** [comment]
thanks a lot
