### ISSUE TITLE
Is there a way to generate HTML report after the test runs?

### ISSUE THREAD

**Issue by rameshrengasamy** [meadsteve/white-bread#72]
I am totally new to this language and i was giving it a try to do automation with this library. Is there a way to generate HTML report after the test runs?

**Comment by meadsteve** [comment]
Hi @rameshrengasamy not at the moment. The feature set of this tool is quite limited at the moment.

**Comment by Dzol** [comment]
Hi @meadsteve,

I'd like to pick this up as we're running White Bread on a CI server where HTML reports would integrate well with the UI.

I hope these can make it into master:

### Minimal Modifications + Additions

* Reach out to configuration for fetching [formatters](https://github.com/meadsteve/white-bread/blob/master/lib/white_bread.ex#L14) instead of just the one.
I.e. generalize the line above to read in a (list of) modules with which to format.
* Implement the [progress reporter](https://github.com/meadsteve/white-bread/blob/master/lib/white_bread/outputers/progress_reporter.ex) protocol for and alongside an HTML formatter (somewhat like the [console reporter](https://github.com/meadsteve/white-bread/blob/2804fb1dec56f69f7a9f4e4837d0d073591c557c/lib/white_bread/outputers/console.ex) but as a **generic server**).

### More Extensive Changes

* Replace the `Reporter` protocol and the current console formatter with and event manager based on a [supervisor](https://github.com/elixir-lang/elixir/blob/master/lib/ex_unit/lib/ex_unit/event_manager.ex) and [generic server](https://github.com/elixir-lang/elixir/blob/master/lib/ex_unit/lib/ex_unit/cli_formatter.ex).
* Change the main [Whitebread](https://github.com/elixir-lang/elixir/blob/master/lib/ex_unit/lib/ex_unit/runner.ex#L27-L29) file to start the event manager and the formatters.

If time permits I can make the more extensive changes in a separate PR as they involve structural changes.

**Comment by Dzol** [comment]
@rameshrengasamy: This documents how to do HTML reporting https://github.com/meadsteve/white-bread#html-output

**Comment by rameshrengasamy** [comment]
@Dzol Thank you so much, ill try it out. I got an error when i tried to run mix white_bread.run. It might be my mistake somewhere too, as I m totally new to this framework. But i can try again and post here

** (MatchError) no match of right hand side value: []
    lib/white_bread/command_line/suite_run.ex:34: WhiteBread.CommandLine.SuiteRun.get_suites_from_config/2
    lib/white_bread/command_line/suite_run.ex:13: WhiteBread.CommandLine.SuiteRun.run_suites/2
    lib/mix/tasks/white_bread.run.ex:20: Mix.Tasks.WhiteBread.Run.run/1
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2

**Comment by rameshrengasamy** [comment]
@Dzol I got it working, ended up upgrading my Elixir version, it works now...Thank you

**Comment by Dzol** [comment]
This ticket was never closed which is a good thing because reporters (including the HTML reporter) can only do their thing on a **feature by feature** basis. The limitations are obvious: it would be nice to have a report on a **suite by suite** basis.

Some existing code has to be generalized (i.e. the code responsible for console output) to allow for another reporter which outputs **suite** information.

By that virtue I suggest we make the **more extensive changes** above.

**Comment by Dzol** [comment]
@meadsteve: PR #83 generalizes how reporting is done and improves the HTML reporting.

Here is some HTML output from the test suite (OKs should in fact be green):

<!DOCTYPE html><html><body><h1>White Bread Results</h1><p>Suite: <b>Alternate context</b></p><ul style="list-style-type:square"><li><font color="green">OK:</font> Table with step</li><li><font color="green">OK:</font> Background doc string</li><li><font color="green">OK:</font> The desire to have toasted bread</li><li><font color="green">OK:</font> If I had a voice</li><li><font color="green">OK:</font> Be sad that no coffee is left</li><li><font color="green">OK:</font> If I had a heart</li><li><font color="green">OK:</font> Doc string with step</li><li><font color="green">OK:</font> Buy last coffee</li></ul><p>Suite: <b>Outline context</b></p><ul style="list-style-type:square"><li><font color="green">OK:</font> If I had a voice</li><li><font color="green">OK:</font> If I had a heart</li></ul><p>Suite: <b>Plain context - Songs</b></p><ul style="list-style-type:square"><li><font color="green">OK:</font> The desire to have toasted bread</li><li><font color="green">OK:</font> Table with step</li><li><font color="green">OK:</font> If I had a voice</li><li><font color="green">OK:</font> If I had a heart</li><li><font color="green">OK:</font> Be sad that no coffee is left</li><li><font color="green">OK:</font> Buy last coffee</li><li><font color="green">OK:</font> Background doc string</li><li><font color="green">OK:</font> Doc string with step</li></ul><p>Suite: <b>Singer role</b></p><ul style="list-style-type:square"><li><font color="green">OK:</font> If I had a voice</li><li><font color="green">OK:</font> If I had a heart</li></ul></body></html>
